server:
  port: 8989
  context-path: /bysj
  jsp-servlet:
    init-parameters:
      development: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/bysj?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  #redis
  redis:
    database: 0
    host: 192.168.245.134
    port: 7000
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
    timeout: 0
mybatis:
  type-aliases-package: com.zy.entity
  mapper-locations: classpath:com.zy.mapper/*Mapper.xml      #当自己写mapper的时候需要用

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: #缩略图生成参数
  width: 150
  height: 150
  tracker-list: #TrackerList参数,支持多个
    - 192.168.245.136:22122
